### ISSUE TITLE
交流

### ISSUE THREAD

**Issue by wuworongtong** [zhoub/moira#1]
周波，你好！我有moira的源代码，不知道您是否有意，进一步完善软件？

**Comment by zhoub** [comment]
你好，由于本职工作繁忙，暂时没有可能，非常抱歉。

**Comment by wuworongtong** [comment]
> 你好，由于本职工作繁忙，暂时没有可能，非常抱歉。

好的。能理解！有空时，请留言。

**Comment by wuworongtong** [comment]
理解！祝工作愉快！
